### PR TITLE
HOCS-2493 : detect pushes to hotfix branches

### PR DESCRIPTION
**Pull request by MarkWrightBjss**

### CODE REVIEW

**Review by zuzak — CHANGES_REQUESTED** [review]
This won't work at the moment, as the `docker-build` step only tuns on a push to master or a tag. This means the pipeline'll skip straight to installing a non-existent Docker image.

If you run this locally (`docker exec`) you'll probably get a "cannot push non-existent tag (latest)" error.

**Review by Paulcr-ho — CHANGES_REQUESTED** [review]

**Review by Paulcr-ho — APPROVED** [review]

**Review by zuzak — COMMENTED** [review]
Clearing "request changes" status.

**Review by zuzak — APPROVED** [review]
Oh, apparently I have to explicitly approve it.

**Comment by zuzak** [comment]
Superseded by #109

**Pull request closed without merging**
